-- AlterTable
ALTER TABLE "WebsiteSettings" DROP COLUMN "aboutSubtitle",
DROP COLUMN "aboutTitle",
DROP COLUMN "brandLogoUrl",
DROP COLUMN "enableFeaturedProjects",
DROP COLUMN "enableGallery",
DROP COLUMN "enableHero",
DROP COLUMN "enableImpact",
DROP COLUMN "enableLeadership",
DROP COLUMN "enableNewsletter",
DROP COLUMN "heroLayout",
DROP COLUMN "heroTheme",
DROP COLUMN "milestonesEyebrow",
DROP COLUMN "milestonesTitle",
DROP COLUMN "newsletterCTA",
DROP COLUMN "newsletterSubtitle",
DROP COLUMN "newsletterTitle",
DROP COLUMN "partnerDescription",
DROP COLUMN "partnerSubtitle",
DROP COLUMN "partnerTitle",
DROP COLUMN "portfoliosEyebrow",
DROP COLUMN "portfoliosTitle",
DROP COLUMN "sponsorsImpactCards",
DROP COLUMN "sponsorsTiers",
DROP COLUMN "teamBoardTitle",
ADD COLUMN     "noticeboardEyebrow" TEXT,
ADD COLUMN     "noticeboardTitle" TEXT;

