-- AlterTable
ALTER TABLE "WebsiteSettings" ADD COLUMN     "aboutEyebrow" TEXT,
ADD COLUMN     "aboutPhoto" TEXT,
ADD COLUMN     "aboutSubtitle" TEXT,
ADD COLUMN     "aboutTitle" TEXT,
ADD COLUMN     "accentColor" TEXT DEFAULT '#F4F5F7',
ADD COLUMN     "archiveSubtitle" TEXT,
ADD COLUMN     "archiveTitle" TEXT,
ADD COLUMN     "brandLogoUrl" TEXT,
ADD COLUMN     "darkColor" TEXT DEFAULT '#0B132B',
ADD COLUMN     "enableArchive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableJoin" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enableNewsletter" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "enablePartner" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "eventsCompletedCTA" TEXT,
ADD COLUMN     "eventsCompletedTitle" TEXT,
ADD COLUMN     "eventsEmptyDesc" TEXT,
ADD COLUMN     "eventsEmptyTitle" TEXT,
ADD COLUMN     "eventsEyebrow" TEXT,
ADD COLUMN     "eventsRegisterCTA" TEXT,
ADD COLUMN     "eventsSubtitle" TEXT,
ADD COLUMN     "eventsTitle" TEXT,
ADD COLUMN     "eventsUpcomingTitle" TEXT,
ADD COLUMN     "footerDescription" TEXT,
ADD COLUMN     "footerQuickLinks" JSONB,
ADD COLUMN     "footerSocials" JSONB,
ADD COLUMN     "galleryAlbumId" TEXT,
ADD COLUMN     "galleryCTA" TEXT,
ADD COLUMN     "galleryCTALink" TEXT,
ADD COLUMN     "galleryLayout" TEXT DEFAULT 'MASONRY',
ADD COLUMN     "galleryLimit" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "galleryShowFeatured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "galleryShowLatest" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "gallerySubtitle" TEXT,
ADD COLUMN     "galleryTitle" TEXT,
ADD COLUMN     "heroCTALink" TEXT,
ADD COLUMN     "heroLayout" TEXT DEFAULT 'SPLIT',
ADD COLUMN     "heroSecondaryCTA" TEXT,
ADD COLUMN     "heroSecondaryCTALink" TEXT,
ADD COLUMN     "heroTheme" TEXT DEFAULT 'DARK',
ADD COLUMN     "homepageSections" JSONB,
ADD COLUMN     "joinSubtitle" TEXT,
ADD COLUMN     "joinSuccessDesc" TEXT,
ADD COLUMN     "joinSuccessTitle" TEXT,
ADD COLUMN     "joinTitle" TEXT,
ADD COLUMN     "lightColor" TEXT DEFAULT '#FAF9F6',
ADD COLUMN     "milestonesEyebrow" TEXT,
ADD COLUMN     "milestonesTitle" TEXT,
ADD COLUMN     "missionQuote" TEXT,
ADD COLUMN     "newsletterCTA" TEXT,
ADD COLUMN     "newsletterSubtitle" TEXT,
ADD COLUMN     "newsletterTitle" TEXT,
ADD COLUMN     "partnerDescription" TEXT,
ADD COLUMN     "partnerSubtitle" TEXT,
ADD COLUMN     "partnerTitle" TEXT,
ADD COLUMN     "portfoliosEyebrow" TEXT,
ADD COLUMN     "portfoliosTitle" TEXT,
ADD COLUMN     "presMessage" TEXT,
ADD COLUMN     "presName" TEXT,
ADD COLUMN     "presPhoto" TEXT,
ADD COLUMN     "presQuote" TEXT,
ADD COLUMN     "presSignature" TEXT,
ADD COLUMN     "primaryColor" TEXT DEFAULT '#8B5CF6',
ADD COLUMN     "projectsActiveTitle" TEXT,
ADD COLUMN     "projectsCTA" TEXT,
ADD COLUMN     "projectsCTALink" TEXT,
ADD COLUMN     "projectsCompletedTitle" TEXT,
ADD COLUMN     "projectsEmptyDesc" TEXT,
ADD COLUMN     "projectsEmptyTitle" TEXT,
ADD COLUMN     "projectsEyebrow" TEXT,
ADD COLUMN     "projectsSubtitle" TEXT,
ADD COLUMN     "projectsTitle" TEXT,
ADD COLUMN     "secondaryColor" TEXT DEFAULT '#EC4899',
ADD COLUMN     "sponsorsCTA" TEXT,
ADD COLUMN     "sponsorsCTALink" TEXT,
ADD COLUMN     "sponsorsImpactCards" JSONB,
ADD COLUMN     "sponsorsMission" TEXT,
ADD COLUMN     "sponsorsSubtitle" TEXT,
ADD COLUMN     "sponsorsTiers" JSONB,
ADD COLUMN     "sponsorsTitle" TEXT,
ADD COLUMN     "teamBoardTitle" TEXT,
ADD COLUMN     "teamEyebrow" TEXT,
ADD COLUMN     "teamJoinCTA" TEXT,
ADD COLUMN     "teamJoinCTALink" TEXT,
ADD COLUMN     "teamLeadershipTitle" TEXT,
ADD COLUMN     "teamMembersTitle" TEXT,
ADD COLUMN     "teamSubtitle" TEXT,
ADD COLUMN     "teamTitle" TEXT,
ADD COLUMN     "valuesQuote" TEXT,
ADD COLUMN     "visionQuote" TEXT;

-- CreateTable
CREATE TABLE "NavigationItem" (
    "id" TEXT NOT NULL,
    "clubId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "displayOrder" INTEGER NOT NULL DEFAULT 0,
    "visible" BOOLEAN NOT NULL DEFAULT true,
    "external" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "NavigationItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WebsiteMetric" (
    "id" TEXT NOT NULL,
    "clubId" TEXT NOT NULL,
    "number" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "description" TEXT,
    "displayOrder" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "WebsiteMetric_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "NavigationItem" ADD CONSTRAINT "NavigationItem_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WebsiteMetric" ADD CONSTRAINT "WebsiteMetric_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Club"("id") ON DELETE CASCADE ON UPDATE CASCADE;
