export enum MemberType {
  COUNCIL = "COUNCIL",
  DIRECTOR = "DIRECTOR",
  COORDINATOR = "COORDINATOR",
  MEMBER = "MEMBER",
}

export enum Position {
  PRESIDENT = "PRESIDENT",
  SECRETARY = "SECRETARY",
  VICE_PRESIDENT = "VICE_PRESIDENT",
  SERGEANT_AT_ARMS = "SERGEANT_AT_ARMS",
  JOINT_SECRETARY = "JOINT_SECRETARY",
  TREASURER = "TREASURER",
  DIRECTORIAL_COMMITTEE_CHAIR = "DIRECTORIAL_COMMITTEE_CHAIR",
  PUBLIC_RELATION_OFFICER = "PUBLIC_RELATION_OFFICER",
  CLUB_SERVICE = "CLUB_SERVICE",
  COMMUNITY_SERVICE = "COMMUNITY_SERVICE",
  VOCATIONAL_SERVICE = "VOCATIONAL_SERVICE",
  INTERNATIONAL_SERVICE = "INTERNATIONAL_SERVICE",
  LITERARY_SERVICE = "LITERARY_SERVICE",
  MEDIA_SERVICE = "MEDIA_SERVICE",
  PUBLIC_RELATION_SERVICES = "PUBLIC_RELATION_SERVICES",
  PROFESSIONAL_DEVELOPMENT = "PROFESSIONAL_DEVELOPMENT",
  SOCIAL_MEDIA = "SOCIAL_MEDIA",
  PERFORMING_ARTS_HEAD = "PERFORMING_ARTS_HEAD",
  TECHNICAL_SERVICES = "TECHNICAL_SERVICES",
  MANAGEMENT_TEAM_HEAD = "MANAGEMENT_TEAM_HEAD",
  MEMBER = "MEMBER",
  MULTIMEDIA_SERVICE = "MULTIMEDIA_SERVICE",
  PHOTOGRAPHY_SERVICE = "PHOTOGRAPHY_SERVICE",
}

export const councilPositions = [
  Position.PRESIDENT,
  Position.SECRETARY,
  Position.VICE_PRESIDENT,
  Position.SERGEANT_AT_ARMS,
  Position.JOINT_SECRETARY,
  Position.TREASURER,
  Position.PUBLIC_RELATION_OFFICER,
];

export const directorAndCoordinatorPositions = [
  Position.CLUB_SERVICE,
  Position.COMMUNITY_SERVICE,
  Position.VOCATIONAL_SERVICE,
  Position.INTERNATIONAL_SERVICE,
  Position.LITERARY_SERVICE,
  Position.MEDIA_SERVICE,
  Position.PUBLIC_RELATION_SERVICES,
  Position.PROFESSIONAL_DEVELOPMENT,
  Position.SOCIAL_MEDIA,
  Position.PERFORMING_ARTS_HEAD,
  Position.TECHNICAL_SERVICES,
  Position.MANAGEMENT_TEAM_HEAD,
  Position.DIRECTORIAL_COMMITTEE_CHAIR,
  Position.MULTIMEDIA_SERVICE,
  Position.PHOTOGRAPHY_SERVICE,
];

export const allPositions = [
  ...councilPositions,
  ...directorAndCoordinatorPositions,
  Position.MEMBER,
];

export const memberTypes = [
  MemberType.COUNCIL,
  MemberType.DIRECTOR,
  MemberType.COORDINATOR,
  MemberType.MEMBER,
];
